version: '2.2'

volumes:
  config:

services:
  homeassistant:
    build: .
    image: fphammerle/home-assistant
    #read_only: true
    volumes: ['config:/config:rw']
    ports: ['127.0.0.1:8123:8123']
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    # docker-compose >=2.2,<3
    cpus: 2
    mem_limit: 512M
    restart: on-failure

# https://docs.docker.com/compose/compose-file/compose-file-v2/
